# Generated by Django 5.0 on 2023-12-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=50, unique=True)),
                ('skill_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.employees')),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.personality')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.employees')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.hobby')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='hobbies',
            field=models.ManyToManyField(through='project_app.EmployeeHobby', to='project_app.hobby'),
        ),
        migrations.AddField(
            model_name='employees',
            name='personality',
            field=models.ManyToManyField(through='project_app.EmployeePersonality', to='project_app.personality'),
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project_app.employees')),
                ('skill_level', models.CharField(max_length=250)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.skill')),
            ],
        ),
    ]
