# Generated by Django 5.0 on 2023-12-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hobbies',
            field=models.ManyToManyField(null=True, through='project_app.EmployeeHobby', to='project_app.hobby'),
        ),
    ]
