# Generated by Django 5.0 on 2023-12-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_alter_hobby_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='skill_description',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill_type',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='description',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='description',
        ),
    ]
