# Generated by Django 5.0 on 2023-12-13 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_employeeskills_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskills',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.employees'),
        ),
    ]
